# Container image for running ARM64 ILP32 programs.

ARG DOCKER_FROM

FROM ${DOCKER_FROM}

ARG TOOLCHAIN_PREFIX

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN apk add --update tftp-hpa \
	&& rm -rf /tmp/* /var/tmp/*

ENV PATH="${TOOLCHAIN_PREFIX}/bin:${PATH}"

COPY ${TOOLCHAIN_PREFIX}/libilp32 ${TOOLCHAIN_PREFIX}/libilp32/
COPY ${TOOLCHAIN_PREFIX}/lib/ld-linux-aarch64_ilp32.so.1 ${TOOLCHAIN_PREFIX}/lib/

ENV ILP32_RUNNER 1

CMD /bin/bash
